{% set name = "sdeint" %}
{% set version = "0.3.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/sdeint-{{ version }}.tar.gz
  sha256: edee046344abc9350518cc4421e0cd983967cae150d382518bfd84e0306ca64a

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.6
    - tox
    - pip
  run:
    - python >=3.6
    - numpy >=1.17

test:
  imports:
    - sdeint
  commands:
    - pip check
  requires:
    - pip

about:
  home: http://github.com/mattja/sdeint/
  summary: Numerical integration of stochastic differential equations (SDE)
  license: GPL-3.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - ashwinkk23
